version: 2
sources:
  - name: ProSolution
    schema: RAW
    database: CURRICULUM_DB
    quoting:
      identifier: true
    tables:
      - name: ProSolution_Site
        description: "This table contains information about sites, including their code, description, and other relevant details."