name: Deploy dbt models

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  actions: read

concurrency:
  group: 'dbt-deploy'
  cancel-in-progress: false

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache:  'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Download manifest from previous succesful CI run
        uses: dawidd6/action-download-artifact@v3
        with:
          branch: main
          name: dbt-manifest
          path: ./state
          if_no_artifact_found: warn 
          workflow_conclusion: success

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run dbt seed
        run: dbt seed --target prod

      - name: Run dbt build
        run: |
          if [ -f ./state/manifest.json ]; then
            echo "State found. Running Slim CD build..."
            dbt build --target prod --state ./state --select "state:modified+"
          else
            echo "No manifest found, running full dbt build"
            dbt build --target prod
          fi

      - name: Upload manifest for future runs
        uses: actions/upload-artifact@v4
        if: success() 
        with:
          name: dbt-manifest
          path: ./target/manifest.json
          if-no-files-found: error
          retention-days: 7

