name: dbt CI (pull request validation)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  dbt-validate:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_PRIVATE_KEY: /home/runner/.dbt/private_key.pem

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Get Schema ID
        id: get_schema_id
        run: |
          SHA_SHORT=$echo( "${{ github.event.pull_request.head.sha }}" | cut -c1-7 )
          ID="${{ github.event.pull_request.number }}__${SHA_SHORT}"
          CLEAN_ID=$(echo ${ID} | tr '[:lower:]' '[:upper:]')
          echo "SCHEMA_ID=${CLEAN_ID}" >> $GITHUB_ENV

      - name: Write Snowflake private key
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.dbt/private_key.pem
          chmod 600 ~/.dbt/private_key.pem

      - name: Download manifest from previous succesful CI run
        uses: dawidd6/action-download-artifact@v3
        with:
          branch: main
          name: dbt-manifest
          path: ./state
          if_no_artifact_found: warn 
          workflow_conclusion: success

      - name: Use state manifest if present
        run: |
          mkdir -p target
          if [ -f ./state/manifest.json ]; then
            echo "Using manifest from previous successful CI run"
            cp ./state/manifest.json ./target/manifest.json
          else
            echo "No manifest found from previous CI run, proceeding without it"
          fi

      - name: dbt debug
        run: dbt debug --target pr --vars "schema_id: ${{ env.SCHEMA_ID }}"

      - name: Install dbt dependencies
        run: dbt deps --target pr --vars "schema_id: ${{ env.SCHEMA_ID }}"

      - name: Validate changes (Slim CI when state is available)
        run: |
          if [ -f ./state/manifest.json ]; then
            echo "✅ State found. Running Slim CI validation..."
            dbt build --target pr --vars "schema_id: ${{ env.SCHEMA_ID }}" --state ./state --select state:modified+ --defer
          else
            echo "⚠️ No manifest found, running full dbt build"
            dbt build --target pr --vars "schema_id: ${{ env.SCHEMA_ID }}"
          fi
