name: CI schema teardown on PR close

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  dbt-ci-schema-teardown:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_PRIVATE_KEY: /home/runner/.dbt/private_key.pem

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Write Snowflake private key
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.dbt/private_key.pem
          chmod 600 ~/.dbt/private_key.pem

      - name: Capture SCHEMA_ID number
        id: get_schema_id
        run: |
          SHA_SHORT=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
          ID="${{ github.event.pull_request.number }}__${SHA_SHORT}"
          CLEAN_ID=$(echo ${ID} | tr '[:lower:]' '[:upper:]')
          echo "SCHEMA_ID=${CLEAN_ID}" >> $GITHUB_ENV

      - name: dbt deps
        run: dbt deps --target pr

      - name: Drop PR schema
        run: |
          dbt run-operation drop_pr_schemas --target pr --vars "schema_id: $SCHEMA_ID"
